### ISSUE TITLE
Dependency on "remote PHP-interpreters" which is failed to be installed

### ISSUE THREAD

**Issue by AAstakhov** [whitefire/eZ-completion#5]
I've been trying  to install last 1.0.1 version. It has dependency on remote PHP-interpreters (org.jetbrains.plugins.phpstorm-remote-interpreter).
Unfortunately I can't install this plugin "PHP Remote Interpreter" https://plugins.jetbrains.com/plugin/7511?pr=phpStorm in my PhpStorm 7.1. It says plugin is not compatible with my version.
Of course, I could try to update PhpStorm, but I have another idea. Is it possible to make dependency on "PHP Remote Interpreter" optional if I don't need it?

**Comment by whitefire** [comment]
I think it should be possible. I will try my best and let you know! :)

**Comment by whitefire** [comment]
A new version is available for testing here: https://github.com/whitefire/eZ-completion/raw/dev/eZ.jar.
All dependencies are now optional. Try it out and let me know if it works! :)

**Comment by AAstakhov** [comment]
Now in event log i see:
08:23:40 NoClassDefFoundError: Framework.CompletionPreloader@82e0de: com/jetbrains/php/config/commandLine/PhpCommandSettingsBuilder
08:24:14 NoClassDefFoundError: com/jetbrains/php/config/commandLine/PhpCommandSettingsBuilder: com/jetbrains/php/config/commandLine/PhpCommandSettingsBuilder

I see the "eZ" item in the PhpStorm menu but functions from this menu doesn't work.

**Comment by whitefire** [comment]
Does it say anyhing about which class is missing?

**Comment by AAstakhov** [comment]
The only information I can see in the Event Log is above. However, there is also detail view, but I don't believe you can find there a missing class name:

com/jetbrains/php/config/commandLine/PhpCommandSettingsBuilder: com/jetbrains/php/config/commandLine/PhpCommandSettingsBuilder
java.lang.NoClassDefFoundError: com/jetbrains/php/config/commandLine/PhpCommandSettingsBuilder
	at Framework.Console.ConsoleCommandFactory.createConsoleCommand(ConsoleCommandFactory.java:28)
	at Actions.AsseticWatch.actionPerformed(AsseticWatch.java:40)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:162)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:261)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:916)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:231)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:104)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6505)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:520)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by whitefire** [comment]
I will download your PhpStorm version and do some testing!

**Comment by whitefire** [comment]
Making the plugin compatible for both PhpStorm 7.1 and 8.0 proved to be a major hassle.
Would you consider upgrading? Multiple cursors and Behat-support alone is worth it. Promise! :)

**Comment by AAstakhov** [comment]
I'm absolutely sure PhpStorm 8 worth updating. However it has one unpleasant issue for windows users regarding to a remote debugging. I'll try to install PhpStorm 8 side-by-side with my current installation. Thank you for help.
