### ISSUE TITLE
PHP Storm Error

### ISSUE THREAD

**Issue by kaizendeveloper** [whitefire/eZ-completion#7]
Framework.CompletionPreloader@64bc543b: com.jetbrains.php.config.commandLine.PhpCommandSettingsBuilder.create(Lcom/intellij/openapi/project/Project;)Lcom/jetbrains/php/config/commandLine/PhpCommandSettings;

-----------------------------------------------------------------------------------------------------------

Framework.CompletionPreloader@64bc543b: com.jetbrains.php.config.commandLine.PhpCommandSettingsBuilder.create(Lcom/intellij/openapi/project/Project;)Lcom/jetbrains/php/config/commandLine/PhpCommandSettings;
java.lang.NoSuchMethodError: com.jetbrains.php.config.commandLine.PhpCommandSettingsBuilder.create(Lcom/intellij/openapi/project/Project;)Lcom/jetbrains/php/config/commandLine/PhpCommandSettings;
	at Framework.Console.ConsoleCommandFactory.createConsoleCommand(ConsoleCommandFactory.java:28)
	at Framework.Console.ConsoleCommandFactory.runConsoleCommand(ConsoleCommandFactory.java:57)
	at Framework.CompletionPreloader.fetchCompletions(CompletionPreloader.java:59)
	at Framework.CompletionPreloader.projectOpened(CompletionPreloader.java:53)
	at com.intellij.openapi.project.impl.ProjectImpl.c(ProjectImpl.java:400)
	at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:63)
	at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:434)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$1.projectOpened(ProjectManagerImpl.java:98)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.c(ProjectManagerImpl.java:721)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:352)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:220)
	at com.intellij.ide.RecentDirectoryProjectsManager.doOpenProject(RecentDirectoryProjectsManager.java:56)
	at com.intellij.ide.ReopenProjectAction.actionPerformed(ReopenProjectAction.java:61)
	at com.intellij.openapi.wm.impl.welcomeScreen.RecentProjectPanel$2.onClick(RecentProjectPanel.java:124)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.openapi.wm.impl.welcomeScreen.RecentProjectPanel$MyList.processMouseEvent(RecentProjectPanel.java:352)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by whitefire** [comment]
Which version of the plugin and PhpStorm are you running?

**Comment by kaizendeveloper** [comment]
PhpStorm 10.0.3
Plugin version 1.0.2

**Comment by whitefire** [comment]
I just released version 1.0.3. It should take care of things. Remember to update bundle to version 1.0.3 as well! :)

**Comment by whitefire** [comment]
Did a upgrade resolve the issue?

**Comment by kaizendeveloper** [comment]
Yes, issue solved! Sorry, I couldn't get back to you earlier, it doesn't crash anymore! Thank you very much!

**Comment by whitefire** [comment]
Excellent! :-)
